#!/bin/Rscript

rm(list=ls())
load("tst")
load("trn")
source("lastcharT.R")   
source("dateindicator.TEST.R")    
source("probdate4digit.TEST.R")

rm(list=ls())
load("tst")
load("trn")   
source("buildroman.R")            
source("findromanT.R")            
source("findromanFT.R")

rm(list=ls())
load("tst")
load("trn")
source("buildroman.R")            
source("findromanIFT.R")          
source("findromanXT.R")           
source("findromanXFT.R") 

rm(list=ls())
load("tst")
load("trn")         
source("911T.R")                  
source("findverbatT.R")    
       
rm(list=ls())
load("tst")
load("trn")
source("findintegerT.R")           
source("findintegerFT.R")         

rm(list=ls())
load("tst")
load("trn")
source("findinteger0T.R")         
source("findinteger0FT.R")        

rm(list=ls())
load("tst")
load("trn")
source("findromanPERIODT.R")      
source("royalromanT.R")           
